#!/bin/bash
set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run as root: sudo bash install-panel.sh"; exit 1; }

ROOT="$(cd "$(dirname "$0")" && pwd)"
WEB="/var/www/xui-pro-panel"
SNIPPET="/etc/nginx/conf.d/xui-pro-panel-locations.conf"
SITE=""

# Locate the XUI-PRO server block generated by x-ui-pro.sh.
for f in /etc/nginx/sites-available/*; do
  [[ -f "$f" ]] || continue
  if grep -q '#X-UI Admin Panel' "$f"; then SITE="$f"; break; fi
done
[[ -n "$SITE" ]] || { echo "XUI-PRO nginx server block not found."; exit 1; }

# Read the existing XUI port and base path from the same database used by x-ui-pro.sh.
DB="/etc/x-ui/x-ui.db"
[[ -f "$DB" ]] || { echo "XUI database not found: $DB"; exit 1; }
command -v sqlite3 >/dev/null || { echo "sqlite3 is required."; exit 1; }
PORT="$(sqlite3 "$DB" "SELECT value FROM settings WHERE key='webPort' LIMIT 1;")"
BASE="$(sqlite3 "$DB" "SELECT value FROM settings WHERE key='webBasePath' LIMIT 1;")"
PORT="${PORT:-2053}"
BASE="${BASE:-/}"
[[ "$BASE" == /* ]] || BASE="/$BASE"
[[ "$BASE" == */ ]] || BASE="$BASE/"

mkdir -p "$WEB"
cp -a "$ROOT/." "$WEB/"
rm -f "$WEB/install-panel.sh"

# This file is included INSIDE the existing server{} block. Do not put location{} in http{}.
cat > "$SNIPPET" <<EOF2
# XUI-PRO custom panel - managed by panel/install-panel.sh
location = /panel { return 301 /panel/; }

# Custom panel login/logout are forwarded to the existing XUI authentication endpoints.
location = /panel/login {
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Requested-With \$http_x_requested_with;
    proxy_pass http://127.0.0.1:${PORT}${BASE}login;
}
location = /panel/logout {
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Requested-With \$http_x_requested_with;
    proxy_pass http://127.0.0.1:${PORT}${BASE}logout;
}

# Existing XUI session/API, exposed under the custom panel namespace.
location /panel/api/ {
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Requested-With \$http_x_requested_with;
    proxy_pass http://127.0.0.1:${PORT}${BASE}panel/api/;
}

# Static custom UI.
location /panel/ {
    alias ${WEB}/;
    index index.html;
    try_files \$uri \$uri/ /panel/index.html;
}
EOF2

# Add the include inside the existing server{} block exactly once.
if ! grep -Fq "include $SNIPPET;" "$SITE"; then
  sed -i "/^[[:space:]]*root \/var\/www\/html\//a\\\tinclude $SNIPPET;" "$SITE"
fi

nginx -t
systemctl reload nginx

echo
 echo "XUI-PRO custom panel installed."
echo "Panel URL: https://YOUR-DOMAIN/panel/"
echo "XUI port: $PORT"
echo "XUI base path: $BASE"
