const $=s=>document.querySelector(s), content=$("#content"), api=async(path,opt={})=>{const r=await fetch(path,{credentials:"same-origin",headers:{"X-Requested-With":"XMLHttpRequest","Content-Type":"application/json",...(opt.headers||{})},...opt});if(r.status===401){location.href="/panel/login.html";throw Error("unauthorized")}let j;try{j=await r.json()}catch{j={}}if(!r.ok||j.success===false)throw Error(j.msg||j.message||`HTTP ${r.status}`);return j};
const fmt=n=>{n=Number(n||0);if(n<1024)return n.toFixed(0)+" B";let u=["KB","MB","GB","TB"],i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(1)+" "+u[i]};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(x){let t=$("#toast");t.textContent=x;t.style.display="block";setTimeout(()=>t.style.display="none",2200)}
async function dashboard(){let j;try{j=await api("/panel/api/server/status")}catch(e){content.innerHTML=`<div class="notice">Server API unavailable: ${esc(e.message)}</div>`;return}
let s=j.obj||j.data||j;let cpu=Number(s.cpu||s.cpuUsed||0),ram=Number(s.mem?.current||s.mem?.percent||s.memUsed||0),disk=Number(s.disk?.current||s.disk?.percent||0);
content.innerHTML=`<div class="grid">
<div class="card"><div class="stat-label">CPU</div><div class="stat-value">${cpu.toFixed(1)}%</div><div class="metric"><span style="width:${Math.min(cpu,100)}%"></span></div></div>
<div class="card"><div class="stat-label">Memory</div><div class="stat-value">${typeof ram==="number"?ram.toFixed(1):"—"}%</div><div class="metric"><span style="width:${Math.min(ram,100)}%"></span></div></div>
<div class="card"><div class="stat-label">Disk</div><div class="stat-value">${typeof disk==="number"?disk.toFixed(1):"—"}%</div><div class="metric"><span style="width:${Math.min(disk,100)}%"></span></div></div>
<div class="card"><div class="stat-label">Uptime</div><div class="stat-value">${esc(s.uptime||"—")}</div><div class="stat-note">Server status</div></div></div>
<div class="section card"><div class="section-head"><h2>System information</h2></div><div class="form-grid">
<div><span class="stat-label">Xray State</span><div class="stat-value" style="font-size:17px">${esc(s.xray?.state||s.xrayState||"Available")}</div></div>
<div><span class="stat-label">Version</span><div class="stat-value" style="font-size:17px">${esc(s.xray?.version||s.version||"—")}</div></div></div></div>`}
async function inbounds(){try{let j=await api("/panel/api/inbounds/list"),rows=j.obj||j.data||[];if(!Array.isArray(rows))rows=[];content.innerHTML=`<div class="card"><div class="section-head"><h2>Inbounds</h2><button class="btn" id="reload">↻ Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Remark</th><th>Protocol</th><th>Port</th><th>Clients</th><th>Status</th></tr></thead><tbody>${rows.map(x=>{let c=x.clientStats?.length||x.settings?.clients?.length||0;return `<tr><td>${esc(x.remark||"—")}</td><td>${esc(x.protocol)}</td><td>${esc(x.port)}</td><td>${c}</td><td><span class="pill ${x.enable?"good":"bad"}">${x.enable?"Enabled":"Disabled"}</span></td></tr>`}).join("")||`<tr><td colspan="5" class="empty">No inbounds found.</td></tr>`}</tbody></table></div></div>`;$("#reload").onclick=inbounds}catch(e){content.innerHTML=`<div class="notice">Could not load inbounds: ${esc(e.message)}</div>`}}
async function clients(){try{let j=await api("/panel/api/inbounds/list"),ins=j.obj||j.data||[],all=[];for(const i of (Array.isArray(ins)?ins:[])){for(const c of (i.settings?.clients||[]))all.push({...c,inbound:i.remark,protocol:i.protocol,port:i.port})}content.innerHTML=`<div class="card"><div class="section-head"><h2>Clients</h2><button class="btn" id="reload">↻ Refresh</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Email</th><th>Inbound</th><th>Protocol</th><th>Status</th><th>Expiry</th></tr></thead><tbody>${all.map(c=>`<tr><td>${esc(c.email||"—")}</td><td>${esc(c.inbound)}</td><td>${esc(c.protocol)}</td><td><span class="pill ${c.enable?"good":"bad"}">${c.enable?"Enabled":"Disabled"}</span></td><td>${c.expiryTime?new Date(Number(c.expiryTime)).toLocaleString():"Unlimited"}</td></tr>`).join("")||`<tr><td colspan="5" class="empty">No clients found.</td></tr>`}</tbody></table></div></div>`;$("#reload").onclick=clients}catch(e){content.innerHTML=`<div class="notice">Could not load clients: ${esc(e.message)}</div>`}}
function tools(){content.innerHTML=`<div class="tools"><div class="card tool"><h3>🔄 Service status</h3><p>Check the live Xray server state through the panel API.</p><button class="btn" onclick="dashboard()">Check now</button></div><div class="card tool"><h3>💾 Backup</h3><p>The XUI-PRO installer already schedules daily database backups.</p><button class="btn" onclick="toast('Daily backup is managed by x-ui-pro.sh')">Info</button></div><div class="card tool"><h3>🔗 Subscriptions</h3><p>Use the existing X-UI subscription service without changing its /sub/ and /json/ paths.</p><button class="btn" onclick="toast('Subscription service remains on the existing X-UI backend')">Info</button></div></div>`}
function settings(){content.innerHTML=`<div class="card"><h2 style="font-size:16px">Panel Settings</h2><p class="muted">This UI intentionally leaves credentials, ports, certificates and Nginx configuration on the existing XUI-PRO backend. We do not expose secrets in the frontend.</p><div class="notice">Authentication is handled by the existing X-UI session. API requests use the same-origin session, so no server credentials are embedded in JavaScript.</div></div>`}
const pages={dashboard,inbounds,clients,tools,settings};function route(){let p=location.hash.slice(1)||"dashboard";if(!pages[p])p="dashboard";document.querySelectorAll(".nav").forEach(a=>a.classList.toggle("active",a.dataset.page===p));$("#pageTitle").textContent=p==="settings"?"Panel Settings":p[0].toUpperCase()+p.slice(1);pages[p]();} 
document.querySelectorAll(".nav").forEach(a=>a.onclick=()=>{$(".sidebar").classList.remove("open")});$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");$("#refresh").onclick=route;$("#logout").onclick=async()=>{try{await fetch("/logout",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"}})}finally{location.href="/panel/login.html"}};window.addEventListener("hashchange",route);route();